export default {
    UP_SLIDE_LIST:"UP_SLIDE_LIST",
    UP_CLASSFIFY_TOP:"UP_CLASSFIFY_TOP",
    UP_CLASSFIFY_BOTTOM:"UP_CLASSFIFY_BOTTOM",
    UP_DISCOUNTLIST:"UP_DISCOUNTLIST",
    UP_HOT_SHOW_LIST:"UP_HOT_SHOW_LIST",
    UP_SHOW_LIST:"UP_SHOW_LIST",
    UP_TOUR_LIST:"UP_TOUR_LIST",
    //橙plus卡
    UP_EQUITY_LIST:"UP_EQUITY_LIST",
    UP_PLUS_DETAIL:"UP_PLUS_DETAIL"
}