export default {
    UP_SLIDE_LIST:"UP_SLIDE_LIST",
    UP_CLASSFIFY_LIST:"UP_CLASSFIFY_LIST",
    UP_DISCOUNTLIST:"UP_DISCOUNTLIST",
    UP_HOT_SHOW_LIST:"UP_HOT_SHOW_LIST",
    UP_SHOW_LIST:"UP_SHOW_LIST"
}